id: P818FF122
initial_creation_type: input
source_metadata:
  title: 'BA: Gaṇḍavyūhasūtra'
  language: sa
  volumes:
    b1972c7c22894c888f9f299b809ad3d4:
      title: Nidāna
      base_file: Nidāna.txt
      work_id: W2A49AAA3
    bf8b0a958a7e4e4c80bc3ac56778fb6e:
      title: Samantabhadra
      base_file: Samantabhadra.txt
      work_id: W7C669C87
    192e8a86cc4743cda105978a1100852f:
      title: Title
      base_file: Title.txt
      work_id: WE6B8FDC4
  chapter_to_tile: {}
created_at: '2022-03-01T21:27:58.993613'
last_modified_at: '2022-03-01T21:27:58.993619'
